---
title: 'SQL Exercise #2: Querying Movie Data, Extra Exercises - Solutions without
  Code'
output:
  html_document:
    df_print: paged
---

This notebook contains the **solutions without code** for Exercise 2 - Querying Movie Data, Extra Exercises.

```{r setup}
library(DBI)
db = dbConnect(RSQLite::SQLite(), dbname = "movies/data_movies.db")
knitr::opts_chunk$set(connection = "db")
```

## Question 1

Find the names of all reviewers who rated Gone with the Wind.

```{sql, echo = FALSE}
SELECT DISTINCT Reviewer.name
FROM (Rating LEFT JOIN Movie ON Rating.mID = Movie.mID) LEFT JOIN Reviewer ON Rating.rID = Reviewer.rID
WHERE movie.title = 'Gone with the Wind';
```


## Question 2

For any rating where the reviewer is the same as the director of the movie, return the reviewer name, movie title, and number of stars.

```{sql, echo = FALSE}
SELECT DISTINCT Reviewer.name, Movie.title, Rating.stars
FROM (Rating LEFT JOIN Movie ON Rating.mID = Movie.mID) LEFT JOIN Reviewer ON Rating.rID = Reviewer.rID
WHERE Movie.director = Reviewer.name;
```

## Question 3

Return all reviewer names and movie names together in a single list, alphabetized. (Sorting by the first name of the reviewer and first word in the title is fine; no need for special processing on last names or removing "The".)

```{sql, echo = FALSE}
SELECT name
FROM Reviewer
UNION ALL 
SELECT title
FROM Movie
ORDER BY name;
```

## Question 4

Find the titles of all movies *not* reviewed by Chris Jackson.

```{sql, echo = FALSE}
SELECT title
FROM Movie
WHERE mID not in (
    SELECT Rating.mID
    FROM Rating LEFT JOIN Reviewer ON Rating.rID = Reviewer.rID 
    WHERE Reviewer.name = "Chris Jackson");
```

## Question 5

For all pairs of reviewers such that both reviewers gave a rating to the same movie, return the names of both reviewers. Eliminate duplicates, don't pair reviewers with themselves, and include each pair only once. For each pair, return the names in the pair in alphabetical order.

```{sql, echo = FALSE}
SELECT DISTINCT rev1.name AS reviewer1_name, rev2.name AS reviewer2_name
FROM Rating AS rat1, Rating AS rat2, Reviewer AS rev1, Reviewer AS rev2
WHERE rat1.mID = rat2.mID AND
    rat1.rID = rev1.rID AND
    rat2.rID = rev2.rID AND
    rat1.rID != rat2.rID AND
    rev1.name < rev2.name
ORDER BY rev1.name, rev2.name;
```

## Question 6

For each rating that is the lowest (fewest stars) currently in the database, return the reviewer name, movie title, and number of stars.

```{sql, echo = FALSE}
SELECT Reviewer.name, Movie.title, Rating.stars 
FROM (Rating LEFT JOIN Movie ON Rating.mID = Movie.mID) LEFT JOIN Reviewer ON Rating.rID = Reviewer.rID
WHERE Rating.stars = (SELECT MIN(stars) FROM Rating);
```

## Question 7

List movie titles and average ratings, from highest-rated to lowest-rated. If two or more movies have the same average rating, list them in alphabetical order.

```{sql, echo = FALSE}
SELECT Movie.title, AVG(stars) as avg_rating
FROM Rating LEFT JOIN Movie ON Rating.mID = Movie.mID
GROUP BY Rating.mID
ORDER BY avg_rating DESC, Movie.title ASC;
```

## Question 8

Find the names of all reviewers who have contributed three or more ratings. (As an extra challenge, try writing the query without HAVING or without COUNT.)

```{sql, echo = FALSE}
SELECT Reviewer.name
FROM Rating LEFT JOIN Reviewer ON Rating.rID = Reviewer.rID
GROUP BY Rating.rID
HAVING COUNT(Rating.rID) >= 3;
```

## Question 9

Some directors directed more than one movie. For all such directors, return the titles of all movies directed by them, along with the director name. Sort by director name, then movie title. (As an extra challenge, try writing the query both with and without COUNT.)

```{sql, echo = FALSE}
SELECT title, director
FROM Movie
WHERE director in (
    SELECT director
    FROM Movie
    GROUP BY director
    HAVING COUNT(*) > 1)
ORDER BY director, title;
```

## Question 10

Find the movie(s) with the highest average rating. Return the movie title(s) and average rating. (Hint: This query is more difficult to write in SQLite than other systems; you might think of it as finding the highest average rating and then choosing the movie(s) with that average rating.)

```{sql, echo = FALSE}
SELECT Movie.title, AVG(Rating.stars)
FROM Rating LEFT JOIN Movie ON Rating.mID = Movie.mID
GROUP BY Rating.mID
HAVING AVG(Rating.stars) = (
    SELECT MAX(avg_table.avg_stars)
    FROM (
        SELECT AVG(stars) AS avg_stars
        FROM Rating
        GROUP BY mID
    ) AS avg_table
);
```

## Question 11 

Find the movie(s) with the lowest average rating. Return the movie title(s) and average rating. (Hint: This query may be more difficult to write in SQLite than other systems; you might think of it as finding the lowest average rating and then choosing the movie(s) with that average rating.)

```{sql, echo = FALSE}
SELECT Movie.title, AVG(Rating.stars)
FROM Rating LEFT JOIN Movie ON Rating.mID = Movie.mID
GROUP BY Rating.mID
HAVING AVG(Rating.stars) = (
    SELECT MIN(avg_table.avg_stars)
    FROM (
        SELECT AVG(stars) AS avg_stars
        FROM Rating
        GROUP BY mID
    ) AS avg_table
);
```

## Question 12

For each director, return the director's name together with the title(s) of the movie(s) they directed that received the highest rating among all of their movies, and the value of that rating. Ignore movies whose director is NULL.

```{sql, echo = FALSE}
SELECT DISTINCT m1.director, m1.title, r1.stars
FROM Rating AS r1 LEFT JOIN Movie AS m1 ON r1.mID = m1.mID
WHERE m1.director IS NOT NULL AND
    r1.stars IN (
        SELECT MAX(r2.stars)
        FROM Rating AS r2 LEFT JOIN Movie AS m2 ON r2.mID = m2.mID
        WHERE m2.director IS NOT NULL AND m1.director = m2.director
    );
```
